q1-1:
	rm q1-1
	/Users/aravind/Code/simplecpp/s++ q1-1.cpp -o q1-1
	./q1-1

q1-2:
	rm q1-2
	/Users/aravind/Code/simplecpp/s++ q1-2.cpp -o q1-2
	./q1-2

quiz:
	/Users/aravind/Code/simplecpp/s++ quiz.cpp -o quiz
	./quiz