square:
	/Users/aravind/Code/simplecpp/s++ square.cpp -o square.out
	./square.out

triangle:
	/Users/aravind/Code/simplecpp/s++ triangle.cpp -o triangle.out
	./triangle.out

polygon:
	/Users/aravind/Code/simplecpp/s++ polygon.cpp -o polygon.out
	./polygon.out

squares:
	/Users/aravind/Code/simplecpp/s++ squareInsideSquare.cpp -o squareInsideSquare.out
	./squareInsideSquare.out

dashedLine:
	/Users/aravind/Code/simplecpp/s++ dashedLine.cpp -o dashedLine.out
	./dashedLine.out

# Reference: https://www.youtube.com/watch?v=_r7i5X0rXJk
# target: dependencies
# 	action