square:
	/Users/aravind/Code/simplecpp/s++ square.cpp -o square.out
	./square.out

triangle:
	/Users/aravind/Code/simplecpp/s++ triangle.cpp -o triangle.out
	./triangle.out

polygon:
	/Users/aravind/Code/simplecpp/s++ polygon.cpp -o polygon.out
	./polygon.out

squares:
	/Users/aravind/Code/simplecpp/s++ squareInsideSquare.cpp -o squareInsideSquare.out
	./squareInsideSquare.out

dashedLine:
	/Users/aravind/Code/simplecpp/s++ dashedLine.cpp -o dashedLine.out
	./dashedLine.out

dottedSquare:
	/Users/aravind/Code/simplecpp/s++ dottedSquare.cpp -o dottedSquare.out
	./dottedSquare.out

star:
	/Users/aravind/Code/simplecpp/s++ star.cpp -o star.out
	./star.out

circle7:
	/Users/aravind/Code/simplecpp/s++ circle7.cpp -o circle7.out
	./circle7.out

# Reference: https://www.youtube.com/watch?v=_r7i5X0rXJk
# target: dependencies
# 	action